WIP: Refactor shell scripts
nhs-england-tools/repository-template pull request #137
Opened 2023-10-06 19:09 UTC by stefaniuk

## Description

## Context

## Type of changes

- [ ] Refactoring (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ ] I have followed the code style of the project
- [ ] I have added tests to cover my changes
- [ ] I have updated the documentation accordingly
- [ ] This PR is a result of pair or mob programming

---

## Sensitive Information Declaration

To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this matter.

- [ ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

2023-10-11 08:02 UTC, ballr73 approved these changes

2023-10-12 10:31 UTC, regularfry requested changes
One slight clarification to a comment, otherwise this looks fine.  "Please" isn't usually followed by a comma, and I thought it worth pointing out the details of what it is that we're asking people not to change.

2023-10-12 10:31 UTC, regularfry commented on .github/actions/scan-secrets/action.yaml
> +        # Please, do not change it, as new patterns may be added or history may be rewritten.
```suggestion
        # Please do not change this `check=whole-history` setting, as new patterns may be added or history may be rewritten.
```

2023-10-12 10:31 UTC, regularfry commented on scripts/githooks/check-file-format.sh
> +  is-arg-true "${dry_run:-false}" && dry_run_opt="--dry-run"
Ooh, nice catch

2023-10-12 10:31 UTC, regularfry commented on scripts/githooks/check-file-format.sh
> +is-arg-true "${VERBOSE:-false}" && set -x
👍

2023-10-12 10:58 UTC, regularfry approved these changes

2023-10-12 10:59 UTC, merged