Include default GitHub templates for issue and feature request
nhs-england-tools/repository-template pull request #28
Opened 2023-03-31 12:08 UTC by stefaniuk

2023-04-03 16:54 UTC, walteck requested changes
Couple of comments

2023-04-03 16:54 UTC, walteck commented on .github/SECURITY.md
> +NHS Digital takes security and the protection of private data extremely seriously. If you believe you have found a vulnerability or other issue which has compromised or could compromise the security
Update to "NHS England"

2023-04-03 19:26 UTC, stefaniuk commented on .github/SECURITY.md
> +NHS Digital takes security and the protection of private data extremely seriously. If you believe you have found a vulnerability or other issue which has compromised or could compromise the security
thanks, upddated

2023-04-03 19:26 UTC, stefaniuk commented on .github/SECURITY.md
> +You can send your report to the National Cyber Security Centre, who will assess your report and pass it on to NHS Digital if necessary.
thanks, upddated

2023-05-15 15:15 UTC, walteck approved these changes
LGTM

2023-05-15 15:18 UTC, merged